TP3
martofeld/algoritmos2-tps pull request #13
Opened 2017-11-30 16:56 UTC by martofeld

2017-12-01 16:22 UTC, tutecano1995 commented
A más tardar el finde lo miro!

2017-12-04 04:50 UTC, tutecano1995 requested changes
Les dejo algunos comentarios para que corrijan algunas cosas. Los voy a matar por los archivos duplicados! 😡

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/graph.py
> +        self.edges[information].add(vertex1)
No me gusta que directamente `information` sea la `edge`. Qué pasa si `information` es un _unhashable type_? (Ejemplo una lista).

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/graph.py
> +        # TODO, was not needed yet
Debería estar implementada para que el grafo quede completo!

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/graph.py
> +        return len(self.vertexes.keys())
Podrían usar el `len()` de Python para que les tire la cantidad de vértices

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/graph.py
> +    def get_neighbours(self, vertex):
Esta función queda implementada medio fea por cómo implementaron el grafo. Pero OK, era la única forma de que pase las pruebas con el archivo grande. Personalmente estoy medio en contra de esta implementación, pero bueno, se terminan viendo forzados a hacerlo así por cómo dimos el TP (esto último ya es opinión mía nomás, ni le den bola)

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/graph.py
> +        return vertex1_info.intersection(vertex2_info)
Nuevamente, por la implementación del TP esto no es O(1) (`intersection` no lo es). No tienen mucho para hacer, es la implementación que les terminamos pidiendo... 😞

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/graph_functions.py
> +            return self.lista.pop(0)
Esta operación no es O(1), en Python cuando tienen que sacar un elemento del principio de una lista se desplaza toda la lista y se termina volviendo O(n). Si usan la implementación de cola `deque`, se vuelve O(1) porque está implementada como una doblemente enlazada.

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/graph_functions.py
> +def path(graph, start, end):
Podría llamarse `bfs`

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/graph_functions.py
> +    actors = actors_at_distance(graph, actor, 2)
Podrían usar una _"""constante"""_  (las comillas porque no hay constantes en Python) para el 2, tipo "distancia de popularidad" o algo por el estilo

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/graph_functions.py
> +    print("total de peliculas", movies_count)
Mmm, no me gustan estos `prints` en la función de la librería de funciones! Y son polémicos tantos `for` anidados.

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/graph_functions.py
> +    list = n_steps(graph, actor, distance)
`list` ya está definido en Python, en este caso no rompe porque no hay ningún `list()` después. Pero deberían usar otro nombre. Además no está bueno usar como nombre de variable el tipo de la misma, podrían buscar un nombre más descriptivo (que haga referencia al contenido de la lista y no a que es de tipo `list`).

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/graph_functions.py
> +def similar(graph, vertex, n):
Me explican qué hacen en esta función? Acá están haciendo el random walk?

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/kevin_bacon.py
> +        for char in line:
Por qué hacen todo este lío? Por qué no usan `split`? Si era más complicado el formato podrían haber usado [regex](https://docs.python.org/3/library/re.html)

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/kevin_bacon.py
> +        func = FUNCTIONS.get(args[0], None)
Muy bueno esto 👍

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/main.py
> +KB = "Bacon Kevin"
No me gusta que definan las mismas constantes en dos lugares distintos! Por qué no las importan?

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/main.py
> +def main():
Otro main? Este archivo está de más?

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/seis_grados.py
> +class FifoQueue:
El otro archivo estaba de más, no? Los voy a matar! jajaj
Bueno, misma corrección que en el otro archivo sobre la `FifoQueue`

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/seis_grados.py
> +def path(graph, start, end):
Mismo comentario que en el otro archivo, podría llamarse `bfs`

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/seis_grados.py
> +def actors_at_distance(graph, actor, distance):
Buenísimo, acá corrigen la corrección anterior que les había hecho.

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/seis_grados.py
> +    actors = actors_at_distance(graph, actor, 2)
Misma corrección que en el otro archivo!

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/seis_grados.py
> +    print(movies_count)
No me gusta ese print

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/seis_grados.py
> +    for i in range(random.randint(100, 200)):
No me gustan esos números mágicos 100 y 200

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/seis_grados.py
> +        for j in range(random.randint(20, 30)):
Idem anterior, números mágicos!

2017-12-04 04:50 UTC, tutecano1995 commented on tp3/seis_grados.py
> +def random_walk(graph, vertex, actors):
Podría ser personalizable por parámetro la longitud y cantidad de iteraciones

2017-12-04 14:29 UTC, martofeld commented
@tutecano1995 Ahora reviso todo. No entiendo porque mierda se duplicaron los archivos

2017-12-04 14:42 UTC, martofeld commented on tp3/graph.py
> +        return len(self.vertexes.keys())
Estamos usando len

2017-12-04 14:43 UTC, martofeld commented on tp3/seis_grados.py
> +class FifoQueue:
Si

2017-12-04 14:43 UTC, martofeld commented on tp3/seis_grados.py
> +def actors_at_distance(graph, actor, distance):
Sisi, vas a ver varias que se corrigen automagicamente cuando borre los archivos de mas

2017-12-04 14:56 UTC, martofeld commented on tp3/graph.py
> +        # TODO, was not needed yet
La implementacion queda a cargo del lector

2017-12-04 14:57 UTC, martofeld commented on tp3/graph.py
> +        self.edges[information].add(vertex1)
Me vas a hacer escribir un TDA que solo tenga information adentro? Tengo que cambiar muchas cosas si lo hago. Podemos simplemente asumir que es una precondicion?

2017-12-04 15:46 UTC, tutecano1995 commented on tp3/graph.py
> +        return len(self.vertexes.keys())
Lo que digo es que se pueda obtener la cantidad de vértices haciendo `len(grafo)`, usando `__len__`

2017-12-04 15:48 UTC, tutecano1995 commented on tp3/graph.py
> +        # TODO, was not needed yet
Jajaja, es bastante simple la implementación, si tienen tiempo háganla

2017-12-04 15:48 UTC, tutecano1995 commented on tp3/graph.py
> +        self.edges[information].add(vertex1)
Mmm, lo ideal sería que lo implementen. Si están cortos de tiempo y prefieren dejarlo así, avísenme.

2017-12-04 23:52 UTC, martofeld commented on tp3/graph.py
> +        self.edges[information].add(vertex1)
No estoy corto de tiempo, solo no tenia muchas ganas. Si no lo implementamos nos bajas puntos?

2017-12-04 23:54 UTC, martofeld commented on tp3/graph.py
> +        return len(self.vertexes.keys())
Me parece que asi es mas claro, sino si mañana cambia a que llamamos "largo" del grafo tambien romperia esta primitiva

2017-12-05 02:56 UTC, tutecano1995 commented on tp3/graph.py
> +        return len(self.vertexes.keys())
Oka! Esta bien así

2017-12-05 03:25 UTC, tutecano1995 commented on tp3/graph.py
> +        return id(self)
Esto está mal, `id()` devuelve la posición en memoria, entonces dos objetos iguales se estarían hasheando a lugares distintos. Miren, otra vez van a tener el mismo problema de hashear un potencial objeto _unhashable_. Ya fue, si pueden tiren una excepción o vuelvan a lo que tenían antes. Todo esto es el problema de la implementación de mierda que les hacemos hacer para que pase el grafo grande (realmente les pido perdón por hacer esto en el TP3, estoy indignado).

2017-12-06 04:12 UTC, tutecano1995 approved these changes
Bueno! Les quedó bien. Como podrán ver no me gusta para nada la implementación del grafo, pero no los culpo por eso y no les voy a restar puntos por eso tampoco (porque era la única forma para que les funcione). El resto está en general bien, así que después de la extorsión que sufrí por parte de @martofeld les dejo un 10. Felicitaciones @Mile97 y @martofeld!

2017-12-06 04:12 UTC, tutecano1995 commented on tp3/seis_grados.py
> +from queue import Queue
Podrían haber usado `deque`, `queue` apunta más a programas concurrentes según tengo entendido. Incluso, internamente debe estar implementada con `deque`, igualmente no está mal (es solo un comentario).

2017-12-06 04:12 UTC, tutecano1995 commented on tp3/seis_grados.py
> +def bfs(graph, start, end):
Ok, le cambiaron el nombre 👌

2017-12-06 04:12 UTC, tutecano1995 commented on tp3/kevin_bacon.py
> +        args = re.split("\s(?=')", line.strip())
Mucho mejor!

2018-10-15 12:57 UTC, merged